facility_definitions:
  PlantFacility:
    children:
      distribution:
        class: DistributionUnit
      storage:
        class: StorageUnit
    class: SupplierFacility
    datamodel: FacilityDataModel
    products:
      class: ProductUnit
      config:
        consumer:
          class: ConsumerUnit
        manufacture:
          class: ManufactureUnit
  StoreFacility:
    children:
      storage:
        class: StorageUnit
    class: OuterRetailerFacility
    config:
      datetime_column: Date
      demand_column: Demand
      dynamics_sampler_type: processed_price_demand
      file_path: /path/to/data.csv
      price_column: Price
      sku_column: SkuName
    datamodel: FacilityDataModel
    products:
      class: StoreProductUnit
      config:
        consumer:
          class: ConsumerUnit
        seller:
          class: OuterSellerUnit
          config:
            sale_hist_len: 14
  SuperVendor:
    children:
      distribution:
        class: DistributionUnit
      storage:
        class: SuperStorageUnit
    class: SupplierFacility
    datamodel: FacilityDataModel
    products:
      class: ProductUnit
  WarehouseFacility:
    children:
      distribution:
        class: DistributionUnit
      storage:
        class: StorageUnit
    class: WarehouseFacility
    products:
      class: ProductUnit
      config:
        consumer:
          class: ConsumerUnit
mix_distribution:
  config:
    air:
      number: 4
    train:
      number: 140
multi_storage:
  config:
  - capacity: 80000
    id: 1
    unit_storage_cost: 0.1
  - capacity: 80000
    id: 2
    unit_storage_cost: 0.1
policy_parameter:
  facilities:
    Plant:
      max_price: 100
    Store_4803:
      max_price: 100
    Store_4830:
      max_price: 100
    Store_6505:
      max_price: 100
settings:
  pending_order_len: 4
  start_date_time: '2021-07-01'
simple_distribution: &id001
  config:
    train:
      number: 140
single_storage: &id002
  config:
    capacity: 80000
    unit_storage_cost: 0.1
super_distribution:
  config:
    train:
      number: null
super_storage:
  config:
    capacity: null
    unit_storage_cost: 0
world:
  facilities:
  - children:
      distribution: *id001
      storage: *id002
    config:
      unit_delay_order_penalty: 1000
      unit_order_cost: 1.0
    definition_ref: PlantFacility
    name: Plant
    skus:
      供港生菜600G:
        has_manufacture: true
        init_stock: 10000
        max_manufacture_rate: 10000
        price: 6.86172405648495
        sub_storage_id: 0
        unit_delay_order_penalty: 1000
        unit_order_cost: 0
        unit_product_cost: 0
  - children:
      storage: *id002
    config:
      file_path: maro/simulator/scenarios/supply_chain/topologies/walmart/walmart_data/4803.csv
      unit_order_cost: 1.0
    definition_ref: StoreFacility
    name: Store_4803
    skus:
      供港生菜600G:
        backlog_ratio: 0.1
        has_consumer: true
        has_seller: true
        init_stock: 0
        price: 0.0
        sale_gamma: 60
        sub_storage_id: 0
        unit_order_cost: 2.0
  - children:
      storage: *id002
    config:
      file_path: maro/simulator/scenarios/supply_chain/topologies/walmart/walmart_data/4830.csv
      unit_order_cost: 1.0
    definition_ref: StoreFacility
    name: Store_4830
    skus:
      供港生菜600G:
        backlog_ratio: 0.1
        has_consumer: true
        has_seller: true
        init_stock: 0
        price: 0.0
        sale_gamma: 60
        sub_storage_id: 0
        unit_order_cost: 2.0
  - children:
      storage: *id002
    config:
      file_path: maro/simulator/scenarios/supply_chain/topologies/walmart/walmart_data/6505.csv
      unit_order_cost: 1.0
    definition_ref: StoreFacility
    name: Store_6505
    skus:
      供港生菜600G:
        backlog_ratio: 0.1
        has_consumer: true
        has_seller: true
        init_stock: 0
        price: 0.0
        sale_gamma: 60
        sub_storage_id: 0
        unit_order_cost: 2.0
  skus:
  - id: 183676
    name: 供港生菜600G
  topology:
    Store_4803:
      供港生菜600G:
        Plant:
          train:
            cost: 1
            vlt: 2
    Store_4830:
      供港生菜600G:
        Plant:
          train:
            cost: 1
            vlt: 2
    Store_6505:
      供港生菜600G:
        Plant:
          train:
            cost: 1
            vlt: 2
